---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource 
      azure_rm_resourcegroup:
        name: table10rsansibletest
        location: centralindia
        state: absent
        force: true
