- name: Delete Resource Group and  VM
  hosts: localhost
  connection: local
  tasks:
  - name: Delete resource group
    azure_rm_resourcegroup:
      name: table10rsvmrg
      location: centralindia
      state: absent
      force: true
